name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Important for trusted publishing
      contents: read   # Important for trusted publishing
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Build package
      run: uv build
    
    - name: Check package
      run: uv tool run twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No API token needed with trusted publishing
      # The repository must be configured in PyPI for trusted publishing
      # See: https://docs.pypa.io/en/stable/trusted-publishers/
